language: python
sudo: false
python:
  - "pypy"
  - "pypy3"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov
  - pip install tinydb
script:
  py.test -v --cov tinydb_keystore
after_success:
  coveralls